#################################################################
# Creates a base CentOS 6 image with Oracle Java 7
#
#                    ##        .
#              ## ## ##       ==
#           ## ## ## ##      ===
#       /""""""""""""""""\___/ ===
#  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
#       \______ o          __/
#         \    \        __/
#          \____\______/
#
# Author:    Paolo Antinori <paolo.antinori@gmail.com>
# License:   MIT
#################################################################

FROM openjdk7:maven

MAINTAINER Paolo Antinori <paolo.antinori@gmail.com>

RUN yum install -y iptables

